language: android
jdk: openjdk7
android:
  components:
    - build-tools-21.0.2
    - build-tools-21.0.0
    - build-tools-20.0.0
    - android-20
    - android-21
    - extra-android-support
    - extra-android-m2repository
  licenses:
    - '.+'

after_success:
  - if [[ $TRAVIS_PULL_REQUEST == 'false' && $TRAVIS_TAG ]]; then ./gradlew build uploadArchives -PNEXUS_USERNAME="${nexusUsername}" -PNEXUS_PASSWORD="${nexusPassword}" -PnexusUsername="${nexusUsername}" -PnexusPassword="${nexusPassword}" ; fi

script:
  - ./gradlew clean assemble check
